import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import { GeneratedTrip } from '@/types'

const resend = new Resend(process.env.RESEND_API_KEY)

function generateItineraryText(trip: GeneratedTrip): string {
  const lines: string[] = [
    `✈️ ${trip.title}`,
    `📍 ${trip.destination}, ${trip.country}`,
    `💰 Estimated Cost: $${trip.totalEstimatedCost?.toLocaleString()}`,
    ``,
    trip.summary,
    ``,
    `🌤️ ${trip.weatherExpectation}`,
    `📅 Best time: ${trip.bestTimeToVisit}`,
    ``,
    `─────────────────────────`,
    `📋 ITINERARY`,
    `─────────────────────────`,
  ]

  trip.itinerary?.forEach(day => {
    lines.push(``, `DAY ${day.day}: ${day.theme}`)
    lines.push(`🌅 Morning: ${day.morning.title} — ${day.morning.description}`)
    lines.push(`☀️ Afternoon: ${day.afternoon.title} — ${day.afternoon.description}`)
    lines.push(`🌙 Evening: ${day.evening.title} — ${day.evening.description}`)
    lines.push(`🏨 Stay: ${day.accommodation}`)
  })

  lines.push(``, `─────────────────────────`)
  lines.push(`✈️ FLIGHTS`)
  lines.push(`─────────────────────────`)
  trip.flights?.slice(0, 2).forEach(f => {
    lines.push(`${f.airline} ${f.flightNumber}: ${f.departure} → ${f.arrival} | ${f.departureTime}-${f.arrivalTime} | $${f.price}`)
    lines.push(`Book: ${f.bookingUrl}`)
  })

  lines.push(``, `─────────────────────────`)
  lines.push(`🏨 HOTELS`)
  lines.push(`─────────────────────────`)
  trip.hotels?.slice(0, 2).forEach(h => {
    lines.push(`${h.name} ($${h.pricePerNight}/night) — ${h.neighborhood}`)
    lines.push(`${h.description}`)
    lines.push(`Book: ${h.bookingUrl}`)
  })

  lines.push(``, `─────────────────────────`)
  lines.push(`🍽️ RESTAURANTS`)
  lines.push(`─────────────────────────`)
  trip.restaurants?.slice(0, 5).forEach(r => {
    lines.push(`${r.name} (${r.cuisine}, ${r.priceRange}) — Try: ${r.mustTry}`)
  })

  lines.push(``, `─────────────────────────`)
  lines.push(`💡 TIPS`)
  lines.push(`─────────────────────────`)
  trip.tips?.slice(0, 5).forEach(t => {
    lines.push(`[${t.category}] ${t.title}: ${t.content}`)
  })

  lines.push(``, `─────────────────────────`)
  lines.push(`Generated by WanderAI — Your AI Travel Companion`)

  return lines.join('\n')
}

export async function POST(req: NextRequest) {
  try {
    const { type, trip, email, recipientName } = await req.json()

    if (type === 'text') {
      return NextResponse.json({
        success: true,
        text: generateItineraryText(trip),
      })
    }

    if (type === 'email' && email) {
      const itineraryText = generateItineraryText(trip)

      await resend.emails.send({
        from: 'WanderAI <trips@wanderai.app>',
        to: email,
        subject: `Your Trip Itinerary: ${trip.title}`,
        text: itineraryText,
        html: `
          <div style="font-family: Georgia, serif; max-width: 600px; margin: 0 auto; background: #0a0f0a; color: #e8f0e8; padding: 40px 20px;">
            <h1 style="color: #c8a84b; font-size: 28px; margin-bottom: 8px;">✈️ ${trip.title}</h1>
            <p style="color: #8fa88f; margin-bottom: 4px;">📍 ${trip.destination}, ${trip.country}</p>
            <p style="color: #c8a84b; font-size: 20px; font-weight: bold;">💰 $${trip.totalEstimatedCost?.toLocaleString()}</p>
            <p style="border-left: 3px solid #c8a84b; padding-left: 16px; color: #c0d0c0; font-style: italic;">${trip.summary}</p>
            <pre style="white-space: pre-wrap; font-family: monospace; font-size: 13px; background: #111811; padding: 20px; border-radius: 8px; color: #c0d0c0; border: 1px solid #2a3a2a;">${itineraryText}</pre>
            <p style="color: #4a5a4a; font-size: 12px; margin-top: 20px;">Generated by WanderAI</p>
          </div>
        `,
      })

      return NextResponse.json({ success: true, message: 'Email sent!' })
    }

    return NextResponse.json({ success: false, error: 'Invalid share type' }, { status: 400 })
  } catch (error) {
    console.error('Share error:', error)
    return NextResponse.json({ success: false, error: 'Failed to share' }, { status: 500 })
  }
}
